- hosts: graywolf.library.cmu.edu
  tasks:
  - name: We need a public html directory
    file:
      dest: public_html
      state: directory
  - name: We need an index.html
    copy:
      dest: public_html/index.html
      content: "Hello World!"
